apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: {{.Values.namespace}}
  labels:
    app: demo-app
data:
  storage_account_name: {{.Values.config.storageAccountName | quote}}
  write_container_name: {{.Values.config.writeContainerName | quote}}
  swa_agent_socket_path: {{.Values.config.swaAgentSocketPath | quote}}
  azure_tenant_id: {{.Values.config.azureTenantId | quote}}
  azure_client_id: {{.Values.config.azureClientId | quote}}
  rogue_app_address: {{.Values.config.rogueAppAddress | quote}}
